var step = "*************** step 1 ***************";
console.log(step);
var myFullName = " Pritesh Sawant";
console.log("Full Name:", myFullName);
myFullName = "Pritesh Santosh Sawant";
console.log("Full Name: ",myFullName);
var step = "*************** step 2 ***************";
console.log(step);
var js = "I Love Only JS";
console.log(js);
var step = "*************** step 3 ***************";
console.log(step);
var FirstName = "Pritesh";
console.log("First Name:", FirstName);
var LastName = "Sawant";
console.log( "Last Name:",LastName);
var age = "24";
console.log("age:",age);
var address = "Pune";
console.log("Address:",address);
var pinCode = "423204";
console.log("Pin Code:", pinCode);
var Gender = "Male";
console.log("Gender:", Gender);
var married = "No";
console.log("Is Married: ",married);
